### ISSUE TITLE
Display what command is done

### ISSUE THREAD

**Issue by vikfroberg** [vikfroberg/brb#1]

**Comment by flying-sheep** [comment]
impossible when simply called on the same command line afterwards.

we’d have to change the call to work like `watch`, `xargs` or `find -exec`, i.e. brb needs to actually run it. the way to do it would be

1. determine currently run shell binary (`$SHELL`)
2. launch `$SHELL -e 'stuff'`
3. show notification based on exit code and command run

**Comment by vikfroberg** [comment]
Couldn't you use the history to access the last command?

**Comment by flying-sheep** [comment]
the history is 1. shell-specific and 2. the same command line as the `brb` call will contain the last command. depending on the shell this will only end up in the history once `brb` finished executing

**Comment by vikfroberg** [comment]
Oh I see, that makes sense!

**Comment by flying-sheep** [comment]
This is actually not closed by the PR #3
